from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors
from src.testproject.sdk.drivers.actions import Actions


"""
This pytest test was automatically generated by TestProject
    Project: MyAdvocate
    Package: TestProject.Generated.Tests.MyAdvocate
    Test: verify_user_on_dashboard
    Generated by:   (vladislav@myadvocate.com)
    Generated on 04/24/2022, 15:41:53
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'Login' test."""

    '''
    # (STEP DISABLED)
    # 1. Pause for '1000'ms
    driver.pause(milliseconds=1000)
    '''

    '''
    # (STEP DISABLED)
    # 2. Is 'EstatePlan' present?
    estateplan = driver.find_element(By.XPATH,
    "//button[. = 'Start Estate Plan']")

    '''
