from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors
import project_parameters


"""
This pytest test was automatically generated by TestProject
    Project: MyAdvocate
    Package: TestProject.Generated.Tests.MyAdvocate
    Test: type_pass
    Generated by:   (vladislav@myadvocate.com)
    Generated on 04/24/2022, 15:41:53
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'sign_in' test."""

    # 1. Clear 'Password' contents
    password = driver.find_element(By.XPATH,
                                   "//div[2]/div/input")
    password.clear()

    # 2. Type '{project_parameters.password}' in 'Password'
    password = driver.find_element(By.XPATH,
                                   "//div[2]/div/input")
    password.send_keys(f'{project_parameters.password}')
