from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors
import project_parameters


"""
This pytest test was automatically generated by TestProject
    Project: MyAdvocate
    Package: TestProject.Generated.Tests.MyAdvocate
    Test: type_email
    Generated by:   (vladislav@myadvocate.com)
    Generated on 04/24/2022, 15:41:53
"""


@report_assertion_errors
def test_main(driver):
    """This test was auto generated from steps of the 'Sign in with incorrect password' test."""

    # 1. Clear 'Email' contents
    email = driver.find_element(By.CSS_SELECTOR,
                                "#username")
    email.clear()

    # 2. Type '{project_parameters.email}' in 'Email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#username")
    email.send_keys(f'{project_parameters.email}')
