from selenium.webdriver.common.by import By
from src.testproject.decorator import report_assertion_errors
from subtests import test_type_email
from subtests import test_type_pass
from subtests import test_verify_user_on_dashboard


"""
This pytest test was automatically generated by TestProject
    Project: MyAdvocate
    Package: TestProject.Generated.Tests.MyAdvocate
    Test: sign_in
    Generated by:   (vladislav@myadvocate.com)
    Generated on 04/24/2022, 15:41:53
"""


@report_assertion_errors
def test_main(driver):
    """Login with existing user."""

    # 1. This test was auto generated from steps of the 'Sign in with incorrect password' test
    test_type_email.test_main(driver)

    # 2. This test was auto generated from steps of the 'sign_in' test
    # This step was auto generated from several steps
    test_type_pass.test_main(driver)

    # 3. Click 'rememberme'
    rememberme = driver.find_element(By.XPATH,
                                     "/html/body/div[1]/div/div/div[2]/div[1]/div/form/div[3]/div/input")
    rememberme.click()

    # 4. Click 'Sign in'
    sign_in = driver.find_element(By.XPATH,
                                  "/html/body/div[1]/div/div/div[2]/div[1]/div/form/button")
    sign_in.click()

    # 5. This test was auto generated from steps of the 'Login' test
    # This step was auto generated from several steps
    test_verify_user_on_dashboard.test_main(driver)
